site_name: SpaceONE Developer Guides
site_url: https://spaceone-dev.github.io
site_description: SpaceONE Developer Guides
site_author: SpaceONE Team

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
      - instant
nav:
    - Introduction: introduction.md
    - Achitecture design: 
        - MSA Framework: architecture/msa-framework.md
        - Console Framework: architecture/console-framework.md
        - Plugins: architecture/plugins.md
    - Installation:
        - Docker Compose: installation/docker-compose.md
        - Helm Chart: installation/helm.md
    - API developement:
        - Getting Started: api/getting-started.md
    - Core development:
        - Getting Started: core/getting-started.md
        - Coding Style: core/coding-style.md
    - Console development:
        - Getting Started: console/getting-started.md
        - Coding Style: console/coding-style.md
    - Plugins development:
        - Getting Started: plugins/getting-started.md
        - Coding Style: plugins/coding-style.md
    - API References: api.md

markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - def_list

plugins:
    - search
